### ISSUE TITLE
Build error on Vite + Remix in a Linux production server

### ISSUE THREAD

**Issue by Meolocious** [3d-dice/dice-box#112]
Hi, I've got this issue from Vite while building my project based on Remix framework while using '@3d-dice/dice-box'

Build failed in 9.33s [vite]: Rollup failed to resolve import "@3d-dice/dice-box" from "/XXX". This is most likely unintended because it can break your application at runtime. If you do want to externalize this module explicitly add it to build.rollupOptions.external at viteWarn (file:///XXX/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:65810:17) at onwarn (/AU-FE-Dashboard/node_modules/@remix-run/dev/dist/vite/plugin.js:618:13) at onRollupWarning (file:///XXX/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:65843:5) at onwarn (file:///XXX/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:65505:7) at file:///AU-FE-Dashboard/node_modules/rollup/dist/es/shared/node-entry.js:18514:13 at Object.logger [as onLog] (file:///AU-FE-Dashboard/node_modules/rollup/dist/es/shared/node-entry.js:20162:9) at ModuleLoader.handleInvalidResolvedId (file:///AU-FE-Dashboard/node_modules/rollup/dist/es/shared/node-entry.js:19104:26) at file:///AU-FE-Dashboard/node_modules/rollup/dist/es/shared/node-entry.js:19062:26

I'm importing it in the file I'm using in this way:

import DiceBox from '@3d-dice/dice-box';

and due to I'm on a typescript env I've declared the module with .d.ts file so on this side everything is good as you see here:

`vite v5.3.1 building for production...
✓ 191 modules transformed.
Generated an empty chunk: "healthcheck".
Generated an empty chunk: "set-theme".
build/client/.vite/manifest.json                                    9.64 kB │ gzip:   1.23 kB
build/client/assets/DbUPiV4E.jpg     54.25 kB
build/client/assets/route-WTMg5veF.css                              0.39 kB │ gzip:   0.20 kB
build/client/assets/createFolder-RGYWGYZA.css                       0.41 kB │ gzip:   0.23 kB
build/client/assets/root-eOgwB70Z.css                              31.37 kB │ gzip:   6.07 kB
build/client/assets/healthcheck-l0sNRNKZ.js                         0.00 kB │ gzip:   0.02 kB
build/client/assets/set-theme-l0sNRNKZ.js                           0.00 kB │ gzip:   0.02 kB
build/client/assets/Bv9qDst8.js       0.08 kB │ gzip:   0.10 kB
build/client/assets/route-CqqZoow0.js                               0.43 kB │ gzip:   0.25 kB
build/client/assets/CUIZyE9Q.js                          0.82 kB │ gzip:   0.49 kB
build/client/assets/B_Y_VmLk.js               0.89 kB │ gzip:   0.46 kB
build/client/assets/route-BkRhyt1q.js                               1.21 kB │ gzip:   0.64 kB
build/client/assets/BtNgfF8g.js                       1.42 kB │ gzip:   0.53 kB
build/client/assets/CimgtuOV.js                      1.62 kB │ gzip:   0.75 kB
build/client/assets/route-BpVLokdq.js                               1.85 kB │ gzip:   0.91 kB
build/client/assets/route-CfacxOT7.js                               1.92 kB │ gzip:   0.94 kB
build/client/assets/CmECAMo1.js                   2.23 kB │ gzip:   1.11 kB
build/client/assets/iconBase-MvQiUakS.js                            2.51 kB │ gzip:   1.09 kB
build/client/assets/world.none-iYke4uzm.js                          2.61 kB │ gzip:   1.13 kB
build/client/assets/route-D50qhowD.js                               3.18 kB │ gzip:   1.41 kB
build/client/assets/route-Bnz0S3CI.js                               4.00 kB │ gzip:   1.47 kB
build/client/assets/entry.client-B9w0sEph.js                        4.14 kB │ gzip:   1.56 kB
build/client/assets/route-Bu_x_p8R.js                               4.15 kB │ gzip:   1.69 kB
build/client/assets/route-DS0N3_zK.js                               5.66 kB │ gzip:   2.23 kB
build/client/assets/createFolder.data-nEu97ZsK.js                   6.31 kB │ gzip:   2.48 kB
build/client/assets/jsx-runtime-DtbKUkqS.js                         8.12 kB │ gzip:   3.06 kB
build/client/assets/route-B0IwHce_.js                              13.67 kB │ gzip:   3.98 kB
build/client/assets/root-BDyZtGOY.js                               21.70 kB │ gzip:   8.36 kB
build/client/assets/route-BeKRxKUc.js                              24.22 kB │ gzip:   5.52 kB
build/client/assets/index-CD8QPeSm.js                              59.28 kB │ gzip:  20.33 kB
build/client/assets/components-DuO3SpyI.js                        184.78 kB │ gzip:  59.52 kB
build/client/assets/DiceLogic-kGe4p11e.js                         208.42 kB │ gzip:  45.02 kB
build/client/assets/world.onscreen-ChZz9Hup.js                    391.18 kB │ gzip:  87.26 kB
build/client/assets/Dice-CxyGO8XI.js                              691.39 kB │ gzip: 167.91 kB
build/client/assets/world.offscreen-C5e_o3iU.js                 1,447.26 kB │ gzip: 411.46 kB
✓ built in 5.73s
vite v5.3.1 building SSR bundle for production...
✓ 84 modules transformed.
build/server/.vite/manifest.json                                  0.49 kB
build/server/assets/DbUPiV4E.jpg   54.25 kB
build/server/assets/server-build-DA1unXUw.css                    32.17 kB
build/server/index.js                                           175.78 kB
✓ built in 409ms`

I've builded several times on local to test, both dev and prod version and no error was found. But while building online, on my linux machine, I've got the error I shaerd before.

I tried also other solutions suggested like "externalize this module explicitly add it to build.rollupOptions.external" but it only let my server explode with 100% CPU usage costantly and a good 502 error. I'm stuck into this since the last 8h and I don't really know how to proceed.

Thank you

**Comment by Meolocious** [comment]
The issue was inside my server, so I closed the issue
